### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by santaimpersonator** [svvsdIC/Poseidon#1]
I keep getting a bunch of emails (daily) about an issue in this repository, specifically in yarn.lock:
[https://github.com/svvsdIC/Poseidon/tree/master/Software/Nemo/Pi](https://github.com/svvsdIC/Poseidon/tree/master/Software/Nemo/Pi)

Can someone take a look at this so my inbox doesn't get spammed anymore? I would like to not have to mark any GitHub notifications as spam.

**Comment by maurin** [comment]
@santaimpersonator you have been removed from owner's list by @b0be.  You should no longer receive the security notices.
